### ISSUE TITLE
All rake tasks broken after 2.4 Upgrade

### ISSUE THREAD

**Issue by bascht** [hacken-in/hacken-in#710]
Looks like #708 broke all the rake tasks (or something is whacky with the way we source our environment variables for the uberspace cronjobs):

```
Tasks: TOP => twitter:update_lists => environment
(See full trace by running task with --trace)
rake aborted!
NoMethodError: undefined method `tr' for nil:NilClass
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:37:in `initialize'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:270:in `new'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:270:in `resolve_url_connection'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:258:in `resolve_hash_connection'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:215:in `resolve_connection'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:151:in `block in resolve_all'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:150:in `each'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:150:in `resolve_all'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/connection_handling.rb:69:in `resolve'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/core.rb:46:in `configurations='
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/railtie.rb:117:in `block (2 levels) in <class:Railtie>'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:27:in `each'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.8/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/home/hacken/hacken-in-production/releases/20170227200527/config/environment.rb:5:in `<top (required)>'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/hacken/hacken-in-production/shared/bundle/ruby/2.2.0/gems/bugsnag-3.0.0/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
Tasks: TOP => radar:fetch => environment
(See full trace by running task with --trace)
```

Also: Bugsnag couldn't be bothered to tell us, so that config is probably broken as well. 🙈

**Comment by moonglum** [comment]
I noticed that this only happens when the environment variables are not set. You adjusted that, so this should be fine now?
